"""empty message

Revision ID: 11f33083301c
Revises: 4bfe7fce7499
Create Date: 2025-10-22 12:19:47.826224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f33083301c'
down_revision = '4bfe7fce7499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('preinscrits')
    op.drop_table('admis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admis',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preinscrits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nationalite', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nom_prenom', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date_naissance', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lieu_naissance', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sexe', sa.VARCHAR(length=10), nullable=False),
    sa.Column('situation_matrimoniale', sa.VARCHAR(length=50), nullable=False),
    sa.Column('region_origine', sa.VARCHAR(length=100), nullable=False),
    sa.Column('departement_origine', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('langue', sa.VARCHAR(length=10), nullable=False),
    sa.Column('matricule', sa.VARCHAR(length=50), nullable=True),
    sa.Column('departement', sa.VARCHAR(length=100), nullable=False),
    sa.Column('option', sa.VARCHAR(length=100), nullable=False),
    sa.Column('niveau', sa.VARCHAR(length=10), nullable=False),
    sa.Column('diplome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('annee_diplome', sa.INTEGER(), nullable=False),
    sa.Column('annee_academique', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nom_pere', sa.VARCHAR(length=200), nullable=False),
    sa.Column('profession_pere', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telephone_pere', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ville_residence_pere', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nom_mere', sa.VARCHAR(length=200), nullable=False),
    sa.Column('profession_mere', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telephone_mere', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ville_residence_mere', sa.VARCHAR(length=100), nullable=False),
    sa.Column('photo_filename', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pdf_filename', sa.VARCHAR(length=200), nullable=True),
    sa.Column('date_inscription', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nationalite', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nom_prenom', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date_naissance', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lieu_naissance', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sexe', sa.VARCHAR(length=10), nullable=False),
    sa.Column('situation_matrimoniale', sa.VARCHAR(length=50), nullable=False),
    sa.Column('region_origine', sa.VARCHAR(length=100), nullable=False),
    sa.Column('departement_origine', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('langue', sa.VARCHAR(length=10), nullable=False),
    sa.Column('matricule', sa.VARCHAR(length=50), nullable=True),
    sa.Column('departement', sa.VARCHAR(length=100), nullable=False),
    sa.Column('option', sa.VARCHAR(length=100), nullable=False),
    sa.Column('niveau', sa.VARCHAR(length=10), nullable=False),
    sa.Column('diplome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('annee_diplome', sa.INTEGER(), nullable=False),
    sa.Column('annee_academique', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nom_pere', sa.VARCHAR(length=200), nullable=False),
    sa.Column('profession_pere', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telephone_pere', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ville_residence_pere', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nom_mere', sa.VARCHAR(length=200), nullable=False),
    sa.Column('profession_mere', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telephone_mere', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ville_residence_mere', sa.VARCHAR(length=100), nullable=False),
    sa.Column('photo_filename', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pdf_filename', sa.VARCHAR(length=200), nullable=True),
    sa.Column('date_inscription', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    # ### end Alembic commands ###
