"""empty message

Revision ID: 3afb6356c889
Revises: 11f33083301c
Create Date: 2025-10-24 17:37:40.446384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afb6356c889'
down_revision = '11f33083301c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pays')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pays',
    sa.Column('code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('code_systhag', sa.VARCHAR(length=3), nullable=True),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nationalite', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###
