"""empty message

Revision ID: 4bfe7fce7499
Revises: 
Create Date: 2025-04-16 03:44:54.698977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfe7fce7499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matricule_counter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matricule_counter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('annee', sa.INTEGER(), nullable=False),
    sa.Column('code_classe', sa.VARCHAR(length=10), nullable=False),
    sa.Column('dernier_numero', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee', 'code_classe', name='unique_matricule_counter')
    )
    # ### end Alembic commands ###
